name: Benchmark ABM

on:
  workflow_dispatch:
  push:
    #branches:
#      - master
    paths:
      - 'src/ABM'
      - 'src/Quick*'

#permissions:
#  contents: write
#  deployments: write

jobs:
  benchmark:
    name: Run julia benchmark example
    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        version:
#          - '1'
#        os:
#          - ubuntu-latest
#        arch:
#          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.7.2'
      - name: Cache artifacts and packages
        uses: julia-actions/cache@v1
        id: cache
#      - uses: actions/cache@v1
#        env:
#          cache-name: cache-artifacts
#        with:
#          path: ~/.julia/artifacts
#          key: runner.os−test−env.cache−name−{{ hashFiles('**/Project.toml') }}
#          restore-keys: |
#            runner.os−test−
#            ${{ env.cache-name }}-
#            ${{ runner.os }}-test-
#            ${{ runner.os }}-
      - name: Instantiate
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          julia --project=. -e '
            using Pkg;
            Pkg.instantiate()'
      - name: Benchmark
        run: |
          julia --project=. bench/BenchmarkABM.jl

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Julia benchmark result
          tool: 'julia'
          output-file-path: bench/output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '150%'
          comment-on-alert: true
          fail-on-alert: false
          alert-comment-cc-users: '@manuvanegas'
          #auto-push: false
#          
#      - name: Push results to gh-pages branch
#        run: |
#          git checkout gh-pages
#          git commit -m "Update benchmarks"
#          git push origin gh-pages
#          git push 'https://manuvanegas:${{ secrets.GITHUB_TOKEN }}@github.com/manuvanegas/SpatialRust.git' gh-pages:gh-pages
